# Generated by Django 5.2.16 on 2026-07-25 19:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_order_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], max_length=16)),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('profit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('ordered_at', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='employees.employee')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='imports.importjob')),
            ],
            options={
                'db_table': 'sales',
                'ordering': ('-ordered_at',),
                'indexes': [models.Index(fields=['employee', 'status', 'ordered_at'], name='sales_employe_2039a3_idx'), models.Index(fields=['status', 'ordered_at'], name='sales_status_166cb0_idx')],
            },
        ),
    ]
