# Generated by Django 5.2.16 on 2026-07-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
