# Generated by Django 5.2.16 on 2026-07-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('sales', '0002_sale_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='import_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='imports.importjob'),
        ),
    ]
