# Generated by Django 5.2.16 on 2026-07-28 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('sales', '0003_alter_sale_import_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='imports.importjob'),
        ),
    ]
