# Generated by Django 5.2.16 on 2026-07-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_update_external_order_ids_with_month_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='source',
            field=models.CharField(blank=True, choices=[('Pervichka', 'Pervichka'), ('Baza', 'Baza'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=64),
        ),
    ]
