# Generated by Django 5.2.16 on 2026-08-02 06:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='has_sheet_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
