# Generated by Django 5.2.16 on 2026-08-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_has_sheet_error_alter_sale_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
