# Generated by Django 5.2.16 on 2026-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_client_name_sale_product_name_sale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product_name_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
