# Generated by Django 5.2.16 on 2026-07-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('employees', '0003_employee_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_accounts', to='employees.employee'),
        ),
    ]
