# Generated by Django 5.2.16 on 2026-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_telegramaccount_employee'),
        ('employees', '0004_employee_summary_data'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='telegramaccount',
            constraint=models.UniqueConstraint(fields=('employee',), name='unique_telegram_account_per_employee'),
        ),
    ]
