# Generated by Django 5.2.16 on 2026-07-28 11:55

from django.db import migrations, models
from django.db.models import Count


def deduplicate_telegram_accounts(apps, schema_editor):
    TelegramAccount = apps.get_model("accounts", "TelegramAccount")
    duplicate_employees = (
        TelegramAccount.objects.values("employee_id")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    for entry in duplicate_employees:
        emp_id = entry["employee_id"]
        accounts = list(
            TelegramAccount.objects.filter(employee_id=emp_id).order_by("-updated_at", "-id")
        )
        delete_ids = [acc.id for acc in accounts[1:]]
        TelegramAccount.objects.filter(id__in=delete_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_telegramaccount_employee'),
        ('employees', '0004_employee_summary_data'),
    ]

    operations = [
        migrations.RunPython(deduplicate_telegram_accounts, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='telegramaccount',
            constraint=models.UniqueConstraint(fields=('employee',), name='unique_telegram_account_per_employee'),
        ),
    ]
