# Generated by Django 5.2.16 on 2026-07-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_telegramaccount_unique_telegram_account_per_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='role',
            field=models.CharField(default='MOP', max_length=10),
        ),
    ]
