# Generated by Django 5.2.16 on 2026-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_telegramaccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='rop_authenticated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
