# Generated by Django 5.2.16 on 2026-07-30 02:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesgroup',
            name='group_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesgroup',
            name='leader_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesgroup',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
