# Generated by Django 5.2.16 on 2026-07-30 10:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_salesgroup_group_profit_salesgroup_leader_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesgroup',
            name='group_total_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
