# Generated by Django 5.2.16 on 2026-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_salesgroup_group_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesgroup',
            name='leader_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
