# Generated by Django 5.2.16 on 2026-07-25 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4,32}$', "Employee ID faqat raqamlardan iborat bo'lishi kerak.")])),
                ('full_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ('employee_id',),
            },
        ),
    ]
