# Generated by Django 5.2.16 on 2026-07-25 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='groups.salesgroup'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id', 'is_active'], name='employees_employe_14a2a6_idx'),
        ),
    ]
