# Generated by Django 5.2.16 on 2026-07-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='summary_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
