# Generated by Django 5.2.16 on 2026-07-30 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_summary_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMonthlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(help_text='First day of month (YYYY-MM-01)')),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('source_spreadsheet_id', models.CharField(blank=True, max_length=128)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_monthly_stats', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_stats', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_monthly_stats',
                'ordering': ('-period',),
                'unique_together': {('employee', 'period')},
            },
        ),
    ]
