# Generated by Django 5.2.16 on 2026-07-31 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeemonthlystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RopCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(help_text='Hashed ROP password', max_length=128)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rop_credential', to='employees.employee')),
            ],
            options={
                'db_table': 'rop_credentials',
            },
        ),
    ]
