# Generated by Django 5.2.16 on 2026-07-25 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workbook', models.FileField(upload_to='imports/%Y/%m/%d/')),
                ('checksum', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('created_sales', models.PositiveIntegerField(default=0)),
                ('updated_sales', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_jobs',
                'ordering': ('-created_at',),
            },
        ),
    ]
