# Generated by Django 5.2.16 on 2026-07-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_sales', models.PositiveIntegerField(default=0)),
                ('updated_sales', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_text', models.TextField(blank=True, default='')),
                ('sheet_modified_at', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ('-started_at',),
            },
        ),
    ]
