# Generated by Django 5.2.16 on 2026-07-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='skipped_rows',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
