# Generated by Django 5.2.16 on 2026-08-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_synclog_skipped_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadsheetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(help_text='First day of month (YYYY-MM-01)', unique=True)),
                ('spreadsheet_id', models.CharField(max_length=128)),
                ('spreadsheet_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'spreadsheet_periods',
                'ordering': ('-period',),
            },
        ),
    ]
