# Generated by Django 5.2.16 on 2026-08-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_seed_active_spreadsheet_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='orders_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='synclog',
            name='payroll_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(default='payroll', max_length=16),
        ),
    ]
