# Generated by Django 5.2.16 on 2026-08-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_synclog_orders_hash_synclog_payroll_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='unchanged',
            field=models.BooleanField(default=False),
        ),
    ]
